newblog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Authentication Routes
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//password reset routes
// Password Reset Routes...
   Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
   Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
   Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.token');
   Route::post('password/reset', 'ResetPasswordController@reset');

// categories
   Route::resource('categories', 'CategoryController', ['except' => ['create']]);  //automatically display create,index,update,delete
//Tags
   Route::resource('tags', 'TagController', ['except' => ['create']]);
//Comments
   Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
   Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
   Route::put('comments/{id}/edit', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
   Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
   Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);

Route::get('blog/{slug}', ['uses' => 'BlogController@getSingle', 'as' =>'blog.single']); //index page
Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');
Route::get('about', 'PagesController@getAbout');
Route::get('/', 'PagesController@getIndex');
Route::resource('posts', 'PostController');

Auth::routes();

Route::get('/home', 'HomeController@index');

newblog/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function category(){
      return $this->belongsTo('App\Category');
    }

    public function tags(){
      return $this->belongsToMany('App\Tag');
    }

    public function comments(){
      return $this->hasMany('App\Comment');
    }
}

newblog/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Tag;
use Session;
use App\Category;
use Purifier;
use Image;

class PostController extends Controller
{


   public function __construct(){
$this->middleware('auth');
   }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // create a variable  and store all the blog posts in it from hte database
        $posts = Post::orderBy('id', 'desc')->paginate(10);  //orderBy for reversing

        //return a view
        return view('posts.index')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $categories = Category::all();
       $tags = Tag::all();
       return view('posts.create')->withCategories($categories)->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the data
        $this->validate($request, array(
          'title' => 'required|max:255',
          'slug'  => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
          'category_id' => 'required|integer',
          'body'  => 'required',
          'featured_image' => 'sometimes|image'      //sometimes: only validate it when something i
      ));

        //store in the database
        $post = new Post;
        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->category_id = $request->category_id;
        $post->body = Purifier::clean($request->body);

        if($request->hasFile('featured_image')){
          $image = $request->file('featured_image');
          $filename = time().'.'.$image->getClientOriginalExtension();
          $location = public_path('images/'.$filename);
          Image::make($image)->resize(800, 400)->save($location);

          $post->image = $filename;
        }

        $post->save();

        $post->tags()->sync($request->tags, false);

        Session::flash('success', 'the blog post is successfully saved!');
        //redirect to another page
        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);    //Here Post is existing model
        return view('posts.show')->withPost($post); //show request in post controller
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // find the post in the database and save as variable
        $post = Post::find($id);
        $categories = Category::all();
        $tags = Tag::all();

        // return the view and pass in the variable we previously created
        return view('posts.edit')->withPost($post)->withCategories($categories)->withTags($tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validate the data
        // check whether the updated slug is same or different
        $post = Post::find($id);
        if($request->input('slug') == $post->slug){
            $this->validate($request, array(
            'title' => 'required|max:255',
            'body'  => 'required'));
        }
        else {
                $this->validate($request, array(
                'title' => 'required|max:255',
                'slug'  => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
                'category_id' => 'required|integer',
                'body'  => 'required'
                ));
             }
        //save the data to datbase
        $post = Post::find($id);  // find the existing row of the existing post
        $post->title = $request->input('title');     // data coming from the changed form is coming through request
        $post->slug  = $request->input('slug');
        $post->category_id = $request->input('category_id');
        $post->body = Purifier::clean($request->input('body'));
        $post->save();

        if(isset($request->tags)){
          $post->tags()->sync($request->tags);
        }
        else {
          $post->tags()->sync(array());
        }
        //set flash data with success message
        Session::flash('success', 'This post was successfully saved.');

        //redirect with flash data to posts.show
        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->tags()->detach();
        Storage::delete($post->image);
        $post->delete();
        Session::flash('success', 'the post was successfully deleted');
        return redirect()->route('posts.index');
    }
}

newblog/resources/views/posts/create.blade.php
@extends('main')

@section('title', '| Create New Post')

@section('stylesheets')
   {!! Html::style('css/parsley.css') !!}
   {!! Html::style('css/select2.min.css') !!}
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'link code',
      menubar: false
    });
  </script>
@endsection

@section('content')

   <div class="row">
     <div class="col-md-8 col-md-offset-2">
       <h1>Create New Post</h1>
       <hr>
       {!! Form::open(array('route' => 'posts.store', 'data-parsley-validate' => '', 'files' => true)) !!}

       {{form::label('title', 'Title:')}}
       {{form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255'))}}

       {{Form::label('slug', 'Slug:')}}
       {{Form::text('slug', null, array('class'=>'form-control','required', 'minlength'=>'5','maxlength'=>'255'))}}

       {{Form::label('category_id', 'Category:')}}
       <select class="form-control" name="category_id">
         @foreach($categories as $category)
         <option value="{{ $category->id }}">{{ $category->name }}</option>
         @endforeach
       </select>

       {{Form::label('tags', 'Tags:')}}
       <select class="form-control select2-multi" name="tags[]" multiple="multiple">
         @foreach($tags as $tag)
         <option value="{{ $tag->id }}">{{ $tag->name }}</option>
         @endforeach
       </select>

       {{ Form::label('featured_image', 'Upload feature Image:') }}
       {{ Form::file('featured_image') }}

       {{form::label('body', 'Post Body:')}}
       {{form::textarea('body', null, array('class' => 'form-control'))}}

       {{form::submit('Create Post', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;'))}}

       {!! Form::close() !!}
     </div>
   </div>

@endsection

@section('scripts')
  {!! Html::script('js/parsley.min.js') !!}
  {!! Html::script('js/select2.min.js') !!}

  <script type="text/javascript">
    $('.select2-multi').select2();
  </script>
@endsection

newblog/resources/views/posts/edit.blade.php
@extends('main')

@section('title', '| Edit Blog Post')

@section('stylesheets')
   {!! Html::style('css/select2.min.css') !!}
   <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
   <script>
     tinymce.init({
       selector: 'textarea',
       plugins: 'link code',
       menubar: false
     });
   </script>
@endsection

@section('content')

<form method="POST" action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data">
      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label for="title">Title:</label>
            <textarea type="text" class="form-control input-lg" id="title" name="title" rows="1" style="resize:none;">{{ $post->title }}</textarea>
          </div>

          <div class="form-group">
            <label for="slug">Slug:</label>
            <textarea type="text" class="form-control input-lg" id="slug" name="slug" rows="10">{{ $post->slug }}</textarea>
          </div>

          <label for="category_id">Category:</label>
          <select class="form-control" name="category_id">
            @foreach($categories as $category)
            <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
          </select>

          <label for="tags">Tags:</label>
          <select class="form-control select2-multi" name="tags[]" multiple="multiple">
            @foreach($tags as $tag)
            <option value="{{ $tag->id }}">{{ $tag->name }}</option>
            @endforeach
          </select>

          <div class="form-group ">
            <label for="featured_image" class="form-spacing-top">Update Featured Image:</label>
            <input type="file" name="featured_image" class="form-spacing-top">
          </div>

          <div class="form-group ">
            <label for="body" class="form-spacing-top">Body:</label>
            <textarea type="text" class="form-control input-lg " id="body" name="body" rows="10">{{ $post->body }}</textarea>
          </div>
        </div>

        <div class="col-md-4">
          <div class="well">
            <dl class="dl-horizontal">
              <dt>Created at:</dt>
              <dd>{{ date('M j, Y h:i:sa', strtotime($post->created_at)) }}</dd>
            </dl>

            <dl class="dl-horizontal">
              <dt>Last updated:</dt>
              <dd>{{ date('M j, Y h:i:sa', strtotime($post->updated_at)) }}</dd>
            </dl>
            <hr>

            <div class="row">
              <div class="col-sm-6">
                <a href="{{ route('posts.show', $post->id) }}" class="btn btn-danger btn-block">Back</a>
              </div>

              <div class="col-md-6">
                <button type="submit" class="btn btn-success btn-block">Save</button>
              <input type="hidden" name="_token" value="{{ Session::token() }}">
              {{ method_field('PUT') }}
              </div>
            </div>
          </div>
        </div>
      </div>
</form>﻿

@stop

@section('scripts')
  {!! Html::script('js/select2.min.js') !!}

  <script type="text/javascript">
    $('.select2-multi').select2();
    $('.select2-multi').select2().val({!! json_encode($post->tags()->getRelatedIds()) !!}).trigger('change');
  </script>
@endsection

newblog/resources/views/posts/index.blade.php
@extends('main')

@section('title', '| All Posts')

@section('content')

   <div class="row">
     <div class="col-md-10">
       <h1>All Posts</h1>
     </div>

     <div class="col-md-2">
       <a href="{{route('posts.create')}}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Create</a>
     </div>

     <div class="col-md-12">
       <hr>
     </div>
   </div> <!-- End of the orw -->

   <div class="row">
     <div class="col-md-12">
       <table class="table">
         <thead>
           <th>#</th>
           <th>Title</th>
           <th>Body</th>
           <th>Created At</th>
           <th></th>
         </thead>

         <tbody>
           @foreach($posts as $post)
             <tr>
               <th>{{ $post->id }}</th>
               <td>{{ $post->title }}</td>
               <td>{{ substr(strip_tags($post->body), 0, 50) }}{{ strlen(strip_tags($post->body)) > 50 ? "...":"" }}</td>
               <td>{{ date('M j, Y', strtotime($post->created_at)) }}</td>
               <td><a href="{{ route('posts.show', $post->id) }}" class="btn btn-default btn-sm">View</a><a href="{{ route('posts.edit', $post->id) }}" class="btn btn-default btn-sm">Edit</a></td>
             </tr>
           @endforeach
         </tbody>
       </table>

      <div class="text-center">
        {!! $posts->links(); !!}
      </div>
     </div>
   </div>

@stop

newblog/resources/views/posts/show.blade.php
@extends('main')

@section('title', '| View Post')

@section('content')

 <div class="row">
   <div class="col-md-8">
     <h1>{{ $post->title }}</h1>
     <p class="lead">{!! $post->body !!}</p>

     <hr>

     <div class="tags">
       @foreach($post->tags as $tag)
          <span class="label label-default">{{ $tag->name }}</span>
       @endforeach
     </div>

     <hr>

     <div class="row">
       <div class="col-md-8 col-md-offset-2">
         <h3 class="comments-title"><span class="glyphicon glyphicon-comment"></span>{{ $post->comments()->count() }} Comments</h3>
         @foreach($post->comments as $comment)
            <div class="comment">
              <div class="author-info">
                <img src="{{ "https://www.gravatar.com/avatar/" . md5(strtolower(trim($comment->email))).'?s=50&d=mm' }}" alt="" class="author-image">
                <div class="author-name">
                  <h4>{{ $comment->name }}</h4>
                  <p class="author-time">{{ date('F nS, Y - G:iA', strtotime($comment->created_at)) }}</p>
                </div>
              </div>

              <div class="comment-content">
                {{ $comment->comment }}
                <a href="{{ route('comments.edit', $comment->id) }}" class="btn btn-xs btn-primary" style="margin-left:20px;"><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="{{ route('comments.delete', $comment->id) }}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
              </div>
            </div>
         @endforeach
       </div>
     </div>

     <hr>

     <div class="row">
        <div id="comment-form" class="col-md-8 col-md-offset-2" style="margin-top:50px;">
          {{ Form::open(['route' => ['comments.store', $post->id], 'method' => 'POST']) }}

          <div class="row">
            <div class="col-md-6">
              {{ Form::label('name', "Name:") }}
              {{ Form::text('name', null, ['class' => 'form-control']) }}
            </div>

            <div class="col-md-6">
              {{ Form::label('email', "Email:") }}
              {{ Form::text('email', null, ['class' => 'form-control']) }}
            </div>

            <div class="col-md-12">
              {{ Form::label('comment', "Comment:") }}
              {{ Form::textarea('comment', null, ['class' => 'form-control', 'rows' => '5']) }}

              {{ Form::submit('Add Comment', ['class' => 'btn btn-success btn-block', 'style' => 'margin-top:15px;']) }}
            </div>
          </div>
          {{ Form::close() }}
        </div>
     </div>
   </div>

   <div class="col-md-4">
     <div class="well">
       <dl class="dl-horizontal">
         <label>Url:</label>
         <p><a href="{{ url($post->slug) }}">{{url($post->slug)}}</a></p>
       </dl>

       <dl class="dl-horizontal">
         <label>Category:</label>
         <p>{{ $post->category->name }}</p>
       </dl>

       <dl class="dl-horizontal">
         <label>Last updated:</label>
         <p>{{ date('M j, Y H:ia', strtotime($post->updated_at)) }}</p>
       </dl>

       <hr>

       <div class="row">
         <div class="col-md-6">
           {!! Html::linkRoute('posts.edit', 'Edit', array($post->id), array('class' =>'btn btn-primary btn-block')) !!}
         </div>

         <div class="col-md-6">
           {!! Form::open(['route' => ['posts.destroy', $post->id], 'method'=>'DELETE']) !!}
           {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block']) !!}
           {!! Form::close() !!}
         </div>
       </div>

       <div class="row">
         <div class="col-md-12">
           {{ Html::linkRoute('posts.index', '<< See All Posts', [], ['class' => 'btn btn-default btn-block btn-h1-spacing'])}}
         </div>
       </div>

     </div>
   </div>
 </div>

@endsection