newblog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Authentication Routes
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//password reset routes
// Password Reset Routes...
   Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
   Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
   Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.token');
   Route::post('password/reset', 'ResetPasswordController@reset');

// categories
   Route::resource('categories', 'CategoryController', ['except' => ['create']]);  //automatically display create,index,update,delete
//Tags
   Route::resource('tags', 'TagController', ['except' => ['create']]);
//Comments
   Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
   Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
   Route::put('comments/{id}/edit', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
   Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
   Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);

Route::get('blog/{slug}', ['uses' => 'BlogController@getSingle', 'as' =>'blog.single']); //index page
Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');
Route::get('about', 'PagesController@getAbout');
Route::get('/', 'PagesController@getIndex');
Route::resource('posts', 'PostController');

Auth::routes();

Route::get('/home', 'HomeController@index');

newblog/resources/views/partials/_footer.blade.php
<hr>
<p>Copyright Mohit - All right reserved</p>

newblog/resources/views/partials/_head.blade.php
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mohit's Blog @yield('title')</title>  <!--change this title for each page-->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {{Html::style('css/styles.css')}}
     @yield('stylesheets')
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

newblog/resources/views/partials/_javascript.blade.php
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
</script>

newblog/resources/views/partials/_messages.blade.php
@if(Session::has('success'))
  <div class="alert alert-success" role="alert">
    <strong>Success:</strong> {{Session::get('success')}}
  </div>
@endif

@if(count($errors) > 0)
  <div class="alert alert-danger" role="alert">
    <strong>Errors:</strong>
    <ul>
      @foreach($errors->all() as $error)
        <li>{{$error}}</li>
      @endforeach
    </ul>
  </div>
@endif

newblog/resources/views/partials/_nav.blade.php
<!-- Default bootstrap navbar -->
<nav class="navbar navbar-default">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">Mohit's Blog</a>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li class="{{ Request::is('/') ? "active" : "" }}"><a href="/">Home</a></li>
    <li class="{{ Request::is('blog') ? "active" : "" }}"><a href="/">Blog</a></li>
    <li class="{{ Request::is('about') ? "active" : "" }}"><a href="/about">About</a></li>
    <li class="{{ Request::is('contact') ? "active" : "" }}"><a href="/contact">Contact</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    @if(Auth::check())
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ Auth::user()->name }} <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><a href="{{route('posts.index')}}">Posts</a></li>
        <li><a href="{{route('categories.index')}}">Categories</a></li>
        <li><a href="{{route('tags.index')}}">Tags</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{{ route('logout') }}">Logout</a></li>
      </ul>
    </li>
    @else
    <a href="{{ route('login') }}" class="btn btn-default">Login</a>

    @endif
  </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>